version: '2'
services:

  nginx: # https://hub.docker.com/r/_/nginx/
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "./conf/vhost.d:/etc/nginx/vhost.d:ro"
      - "./conf/certs:/etc/nginx/certs:ro"
      - "./conf/htpasswd:/etc/nginx/htpasswd:ro"
      - "/usr/share/nginx/html"
    networks:
      - middle-end
 
  dockergen: # https://hub.docker.com/r/jwilder/docker-gen/
    image: jwilder/docker-gen
    entrypoint: /bin/sh -c
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    container_name: nginx-gen
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./conf/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl"
    networks:
      - middle-end
    depends_on:
      - nginx
      - nginx-letsencrypt
    entrypoint: /bin/sh -c
    command: ["/usr/local/bin/docker-gen -notify-sighup nginx-proxy -watch -wait 30s:60s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]

  nginx-letsencrypt: # https://hub.docker.com/r/alastaircoote/docker-letsencrypt-nginx-proxy-companion/
# old and malfunctioning version: https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion 
    volumes:
      - "./conf/certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/vhost.d:/etc/nginx/vhost.d:rw"
    volumes_from:
      - nginx
    depends_on:
      - nginx
    restart: always
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
    networks:
      - middle-end

networks:
  middle-end:
    external: true
